//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProjectShopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductImage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductImage()
        {
            this.ProductPivotSizes = new HashSet<ProductPivotSize>();
        }
    
        public int product_img_id { get; set; }
        public string product_img { get; set; }
        public int product_img_product_id { get; set; }
        public int product_img_color_id { get; set; }
        public Nullable<int> product_img_count { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductPivotSize> ProductPivotSizes { get; set; }
    }
}
