//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProjectShopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProductImages = new HashSet<ProductImage>();
        }
    
        public int product_id { get; set; }
        public string product_name { get; set; }
        public string product_price { get; set; }
        public int product_category_id { get; set; }
        public int product_subcategory_id { get; set; }
        public int product_innersubcategory_id { get; set; }
        public string product_discount_rate { get; set; }
        public Nullable<System.DateTime> product_discount_time { get; set; }
        public int product_business_id { get; set; }
    
        public virtual BusinessAccount BusinessAccount { get; set; }
        public virtual Category Category { get; set; }
        public virtual InnerSubcategory InnerSubcategory { get; set; }
        public virtual Subcategory Subcategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductImage> ProductImages { get; set; }
    }
}
