//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProjectShopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserBag
    {
        public int user_bag_id { get; set; }
        public int user_bag_user_id { get; set; }
        public int user_bag_product_id { get; set; }
        public int user_bag_product_img_id { get; set; }
        public Nullable<int> user_bag_product_pivot_id { get; set; }
        public int user_bag_product_count { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ProductImage ProductImage { get; set; }
        public virtual ProductPivotSize ProductPivotSize { get; set; }
        public virtual UserAccount UserAccount { get; set; }
    }
}
